[package]
name = "colorbalance-raw"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "ColorBalance image and RAW decode layer"

[dependencies]
colorbalance-core = { workspace = true, features = ["parallel"] }
fast_image_resize = "6.1.0"
rayon = { workspace = true }
image = { workspace = true }
rawler = "=0.8.0"
kamadak-exif = { workspace = true }
flate2 = "1.1"
thiserror = { workspace = true }

[lints.rust]
unsafe_code = "deny"
