//! Academy Common LUT Format (CLF) v3.0 export and import.
//!
//! CLF is the primary interchange format for ColorBalance profiles. It records
//! the profile transform stages as explicit Matrix process nodes inside a
//! `ProcessList`.
//!
//! Node 1 scales channels (folding exposure scale and neutral channel scale).
//! Node 2 applies the fitted color matrix using the row-vector convention.

use crate::contract::DecodeContract;
use crate::interchange::InterchangeError;
use crate::profile::Profile;
use sha2::{Digest, Sha256};

/// Compute a 16-character sha256 hex digest of a decode contract.
fn decode_contract_digest16(contract: &DecodeContract) -> String {
    let json = serde_json::to_string(contract).unwrap_or_default();
    let hash = Sha256::digest(json.as_bytes());
    let hex = format!("{hash:x}");
    hex[..16.min(hex.len())].to_string()
}

/// Compute or retrieve the profile digest string.
fn profile_digest(p: &Profile) -> String {
    if !p.digest.is_empty() {
        p.digest.clone()
    } else {
        crate::profile::digest(p)
    }
}

/// Export a profile to Academy Common LUT Format (CLF) v3.0 XML.
///
/// The emitted document contains a `ProcessList` with exactly two `Matrix`
/// process nodes:
/// - Node 1: Diagonal matrix with combined channel and exposure scaling.
/// - Node 2: The 3x3 color matrix (row-vector convention).
///
/// The document starts with `<?xml version="1.0" encoding="UTF-8"?>` and uses
/// LF line endings with no CR bytes.
pub fn profile_to_clf(p: &Profile) -> String {
    let p_digest = profile_digest(p);
    let digest12 = &p_digest[..12.min(p_digest.len())];
    let contract_digest16 = decode_contract_digest16(&p.decode_contract);

    let exp = p.transform.exposure_scale;
    let s0 = if exp * p.transform.channel_scale[0] != 0.0 {
        1.0 / (exp * p.transform.channel_scale[0])
    } else {
        0.0
    };
    let s1 = if exp * p.transform.channel_scale[1] != 0.0 {
        1.0 / (exp * p.transform.channel_scale[1])
    } else {
        0.0
    };
    let s2 = if exp * p.transform.channel_scale[2] != 0.0 {
        1.0 / (exp * p.transform.channel_scale[2])
    } else {
        0.0
    };

    let m = p.transform.matrix;

    let camera_str = format!("{} {}", p.camera.make, p.camera.model);

    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
        <ProcessList compCLFversion=\"3.0\" id=\"colorbalance-{digest12}\">\n\
        \x20   <Description>ColorBalance profile {p_digest}</Description>\n\
        \x20   <InputDescriptor>normalized linear camera RGB, decode contract digest {contract_digest16}, camera {camera_str}</InputDescriptor>\n\
        \x20   <OutputDescriptor>linear sRGB D65</OutputDescriptor>\n\
        \x20   <Matrix inBitDepth=\"32f\" outBitDepth=\"32f\">\n\
        \x20       <Description>channel and exposure scaling (row-vector · matrix)</Description>\n\
        \x20       <Array dim=\"3 3\">\n\
        \x20           {s0} 0 0\n\
        \x20           0 {s1} 0\n\
        \x20           0 0 {s2}\n\
        \x20       </Array>\n\
        \x20   </Matrix>\n\
        \x20   <Matrix inBitDepth=\"32f\" outBitDepth=\"32f\">\n\
        \x20       <Description>color matrix (row-vector · matrix)</Description>\n\
        \x20       <Array dim=\"3 3\">\n\
        \x20           {} {} {}\n\
        \x20           {} {} {}\n\
        \x20           {} {} {}\n\
        \x20       </Array>\n\
        \x20   </Matrix>\n\
        </ProcessList>\n",
        m[0][0], m[0][1], m[0][2],
        m[1][0], m[1][1], m[1][2],
        m[2][0], m[2][1], m[2][2],
    )
}

/// Parse the two 3x3 matrices from a generated CLF XML document.
///
/// Scans the subset generated by [`profile_to_clf`], extracting the 3x3 array
/// coefficients from both `Matrix` nodes in document order.
pub fn clf_to_matrices(clf: &str) -> Result<[[[f64; 3]; 3]; 2], InterchangeError> {
    let mut matrices = Vec::with_capacity(2);
    let mut search_from = 0;

    while let Some(start_tag) = clf[search_from..].find("<Array") {
        let tag_open = search_from + start_tag;
        let tag_close = match clf[tag_open..].find('>') {
            Some(idx) => tag_open + idx + 1,
            None => {
                return Err(InterchangeError::Parse(
                    "unclosed <Array> tag in CLF".into(),
                ))
            }
        };

        let end_tag = match clf[tag_close..].find("</Array>") {
            Some(idx) => tag_close + idx,
            None => {
                return Err(InterchangeError::Parse(
                    "missing closing </Array> tag in CLF".into(),
                ))
            }
        };

        let content = &clf[tag_close..end_tag];
        let values: Result<Vec<f64>, _> = content
            .split_whitespace()
            .map(|tok| {
                tok.parse::<f64>().map_err(|e| {
                    InterchangeError::Parse(format!("invalid float '{tok}' in Array: {e}"))
                })
            })
            .collect();
        let values = values?;

        if values.len() != 9 {
            return Err(InterchangeError::Parse(format!(
                "expected 9 float values in 3x3 Array, found {}",
                values.len()
            )));
        }

        let mat: [[f64; 3]; 3] = [
            [values[0], values[1], values[2]],
            [values[3], values[4], values[5]],
            [values[6], values[7], values[8]],
        ];
        matrices.push(mat);

        search_from = end_tag + "</Array>".len();
    }

    if matrices.len() != 2 {
        return Err(InterchangeError::Parse(format!(
            "expected exactly 2 Matrix Array nodes, found {}",
            matrices.len()
        )));
    }

    Ok([matrices[0], matrices[1]])
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::calibration::FittedStages;
    use crate::chart::ChartRevision;
    use crate::contract::DecodeContract;
    use crate::decode::CameraIdentity;
    use crate::profile::{apply_transform, ValidationSummary};

    fn sample_profile() -> Profile {
        let dc = DecodeContract::canonical("libraw", "0.21.1");
        let camera = CameraIdentity {
            make: "Canon".into(),
            model: "EOS R5".into(),
            decoder: "libraw".into(),
            decoder_version: "0.21.1".into(),
        };
        let transform = FittedStages {
            exposure_scale: 1.15,
            channel_scale: [0.92, 1.0, 1.08],
            matrix: [[0.85, 0.10, 0.05], [0.05, 0.90, 0.05], [0.02, 0.08, 0.90]],
        };
        let validation = ValidationSummary {
            mean_delta_e: 0.8,
            max_delta_e: 1.5,
            p95_delta_e: 1.3,
            neutral_max_delta_e: 0.5,
            skin_max_delta_e: 0.6,
            condition_number: 1.2,
            patch_count: 24,
        };
        let mut p = Profile {
            schema_version: "1.0".into(),
            decode_contract: dc,
            camera,
            chart_revision: ChartRevision::ClassicFromNovember2014,
            dataset_digest: "abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234"
                .into(),
            reference_digest: "fedc5678fedc5678fedc5678fedc5678fedc5678fedc5678fedc5678fedc5678"
                .into(),
            transform,
            validation,
            digest: String::new(),
        };
        p.digest = crate::profile::digest(&p);
        p
    }

    #[test]
    fn test_clf_format_and_newlines() {
        let p = sample_profile();
        let clf = profile_to_clf(&p);

        assert!(
            clf.starts_with("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"),
            "CLF must start with XML declaration"
        );
        assert!(!clf.contains('\r'), "CLF must contain no CR bytes");
        assert!(clf.contains("<ProcessList compCLFversion=\"3.0\""));
        assert!(clf.contains("<InputDescriptor>normalized linear camera RGB"));
        assert!(clf.contains("<OutputDescriptor>linear sRGB D65</OutputDescriptor>"));
    }

    #[test]
    fn test_clf_roundtrip_recovers_matrices() {
        let p = sample_profile();
        let clf = profile_to_clf(&p);
        let [m1, m2] = clf_to_matrices(&clf).expect("failed to parse generated CLF");

        let exp = p.transform.exposure_scale;
        let expected_s0 = 1.0 / (exp * p.transform.channel_scale[0]);
        let expected_s1 = 1.0 / (exp * p.transform.channel_scale[1]);
        let expected_s2 = 1.0 / (exp * p.transform.channel_scale[2]);

        let expected_m1 = [
            [expected_s0, 0.0, 0.0],
            [0.0, expected_s1, 0.0],
            [0.0, 0.0, expected_s2],
        ];

        for r in 0..3 {
            for c in 0..3 {
                assert!(
                    (m1[r][c] - expected_m1[r][c]).abs() < 1e-12,
                    "m1[{r}][{c}] mismatch: {} vs {}",
                    m1[r][c],
                    expected_m1[r][c]
                );
                assert!(
                    (m2[r][c] - p.transform.matrix[r][c]).abs() < 1e-12,
                    "m2[{r}][{c}] mismatch: {} vs {}",
                    m2[r][c],
                    p.transform.matrix[r][c]
                );
            }
        }
    }

    #[test]
    fn test_clf_sequence_matches_apply_transform() {
        let p = sample_profile();
        let clf = profile_to_clf(&p);
        let [m1, m2] = clf_to_matrices(&clf).expect("failed to parse generated CLF");

        let test_inputs = [
            [0.1, 0.2, 0.3],
            [0.25, 0.35, 0.45],
            [0.5, 0.4, 0.3],
            [0.05, 0.08, 0.12],
            [0.6, 0.55, 0.5],
        ];

        for input in test_inputs {
            let v1 = [
                input[0] * m1[0][0] + input[1] * m1[1][0] + input[2] * m1[2][0],
                input[0] * m1[0][1] + input[1] * m1[1][1] + input[2] * m1[2][1],
                input[0] * m1[0][2] + input[1] * m1[1][2] + input[2] * m1[2][2],
            ];

            let v2 = [
                v1[0] * m2[0][0] + v1[1] * m2[1][0] + v1[2] * m2[2][0],
                v1[0] * m2[0][1] + v1[1] * m2[1][1] + v1[2] * m2[2][1],
                v1[0] * m2[0][2] + v1[1] * m2[1][2] + v1[2] * m2[2][2],
            ];

            let (direct, flags) = apply_transform(&p, input);
            assert_eq!(flags, 0, "test input should not clip");

            for c in 0..3 {
                assert!(
                    (v2[c] - direct[c]).abs() < 1e-9,
                    "channel {c} mismatch: {} vs {}",
                    v2[c],
                    direct[c]
                );
            }
        }
    }

    #[test]
    fn test_clf_parse_error_handling() {
        assert!(clf_to_matrices("not xml").is_err());
        assert!(clf_to_matrices("<ProcessList><Array>1 2 3</Array></ProcessList>").is_err());
        assert!(
            clf_to_matrices("<ProcessList><Array>1 2 3 4 5 6 7 8 9</Array></ProcessList>").is_err()
        );
    }
}
